# 移除version声明（现代Compose不需要）
services:
  app:
    build: .
    ports:
      - "80:8080"
    environment:
      MYSQL_HOST: 172.17.0.1  # 使用宿主机访问已有MySQL容器
      MYSQL_USER: root
      MYSQL_PASSWORD: yourpassword
      MYSQL_DATABASE: bangbangfun
    platform: linux/x86_64      
    # 移除depends_on配置